version: '3'
services:
  dev:
    image: python-growi
    container_name: python-growi-conrainer

    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - .:/workspace:cached
      - ~/.zshrc:/root/.zshrc
      - ~/.vimrc:/root/.vimrc
      - ~/.gitconfig:/root/.gitconfig

    tty: true
    command: /bin/sh -c "while sleep 1000; do :; done"